# Question 1

In [3]:
import numpy as np
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

x = np.matrix(X)
y = np.matrix(Y)
res = x+y
print(res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


# Question 2

In [8]:
import numpy as np
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

res = np.dot(X,Y)
print(res)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Question 3

In [9]:
import numpy as np
matrix=[[1,2,3],[4,5,6]]
print(np.transpose(matrix))

[[1 4]
 [2 5]
 [3 6]]


# Question 4

In [10]:
sen = input("Enter string")
words = sen.split()
words.sort()
for i in words:
    print(i)

Enter stringMy name is Apoorv
Apoorv
My
is
name


# Question 5

In [15]:
punctuations = "!"
sentence = "My name! is!! Apoorv"
for i in sentence:
    if punctuations not in i:
        res+=i
print(res)

My name is Apoorv
